# Site settings
title: Myzsh
email: about@myzsh.io
description: "A framework for modifying a zsh prompt"
langs:
  - langcode: en
    lang_string: Englisha

# Build settings
exclude: [bin, vendor, CNAME, Gemfile, Gemfile.lock, README.md, style.scss]
markdown: rdiscount
rdiscount:
  extensions: [smart]
# Same as GitHub Pages
# https://help.github.com/articles/using-jekyll-with-pages#troubleshooting
safe: true
lsi: false
pygments: true
host: 127.0.0.1
